environment:
  # Visual Studio Version
  MSVS_VERSION: 2013
  # Test against these versions of Node.js and io.js
  matrix:
    # node.js
    - nodejs_version: "6"

# Build on both platforms
platform:
  - x64

shallow_clone: true

before_build:

build_script:
  - build.cmd
  - npm_update.cmd

test: off

test_script:
  #- nuget restore tests\Tests.sln
  #- test.cmd

deploy_script:
  #- deploy.cmd
