environment:
  # Visual Studio Version
  MSVS_VERSION: 2013
  # Test against these versions of Node.js and io.js
  matrix:
    # node.js
    - nodejs_version: "6"

# Build on both platforms
platform:
  - x64

shallow_clone: true

# Install scripts. (runs after repo cloning)
install:
  # Get the latest version of $env:nodejs_version
  - ps: >-
      If($env:nodejs_version -eq "0.8") {
        Install-Product node $env:nodejs_version $env:platform
      } Else {
        Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform
      }
  # Install latest NPM only for node.js versions until built in node-gyp adds io.js support
  # Update is required for node.js 0.8 because built in npm(node-gyp) does not know VS2013
  - ps: >-
      If($env:nodejs_version.Length -ne 1) {
        npm -g install npm 2>&1>$null
        $env:PATH = $env:APPDATA + "\npm;" + $env:PATH
      }
  # Output useful info for debugging.
  - ps: node --version
  - ps: npm --version


before_build:

build_script:
  - build.cmd
  - npm_update.cmd

test: off

test_script:
  #- nuget restore tests\Tests.sln
  #- test.cmd

deploy_script:
  #- deploy.cmd
